# hoshinova configuration file
# Copy this file to config.toml and update it as needed.

[ytdlp]
executable_path = "yt-dlp"
working_directory = "temp"
args = [
  "--embed-thumbnail", "--add-metadata", "--embed-chapters",
  "--concurrent-fragments", "4",
  "--windows-filenames",
  "--js-runtimes", "node",
  "--output", "%(upload_date)s %(title)s [%(channel)s] (%(id)s).%(ext)s"
]
# Format selector passed to yt-dlp -f
format = "bestvideo+bestaudio/best"
# Download from the beginning of the stream (recommended for archiving, add manually if needed)
# Add "--live-from-start" to args if you want this behaviour, literally broken as of now when used with cookies https://github.com/yt-dlp/yt-dlp/issues/15274
# Delay between starting yt-dlp processes. Increase this number if you get
# rate limited by YouTube.
delay_start = "1s"
# Cookies file for member-only streams (Netscape format, export with a browser extension)
# cookies_file = "/path/to/cookies.txt"

[scraper.rss]
poll_interval = "30s"
# Ignore videos older than this. Helps prevent hitting the rate limit on startup
# if a lot of older non-live videos match your filters.
ignore_older_than = "24h"

[notifier.discord]
webhook_url = "https://discordapp.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyz"
notify_on = ["waiting", "recording", "done", "failed"]

# A web interface to view and manage tasks.
# Optional, remove this section to disable.
[webserver]
bind_address = "0.0.0.0:1104"
# Path to a unix socket to listen on instead of / in addition to a TCP port.
# unix_path = "/tmp/hoshinova.sock"

[[channel]]
id = "UCP0BspO_AMEe3aQqqpo89Dg"
name = "Moona Hoshinova"
filters = ["(?i)MoonUtau|Karaoke|Archive"]
# By default, filters will only match the video title. Set this to true if you
# want them to also match the video description.
match_description = false
outpath = "./videos/moona"

# Add more channels...
# [[channel]]
# id = "..."
# name = "..."
# filters = [...]
# match_description = ...
# outpath = "..."
